alias ..='cd ..'
alias ...='cd ../..'
alias chmod='chmod -c'
alias chown='chown -c'
alias cp='cp -iv'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ip='ip --color=auto'
alias ll='ls -hAlF'
alias ls='ls --color=auto'
alias mkdir='mkdir -pv'
alias mtr='sudo mtr -o LSD\ NBAW\ X'
alias mv='mv -iv'
alias rem='rem -mb1 -g -q -@2,0'
alias gitHEAD="git remote show origin | awk '/HEAD/{print \$NF}'"
alias gitRoot='cd "$(git rev-parse --show-cdup)"'
alias rm='rm -iv'
alias sa='alias -p > ~/.bash_aliases'
alias tkremind='tkremind -mb1 -g'
alias vim='vim -p'
alias vimO='vim -O'
