alias ..='cd ..'
alias ...='cd ../..'
alias cgrep='grep --color=always'
alias cp='cp -iv'
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias gvim='gvim -p'
alias l='ls -CF'
alias l.='ls -d .*'
alias la='ls -A'
alias ld='ls -d */'
alias ll='ls -hAlF --time-style=+%F\ %T'
alias ls='ls --color=auto'
alias mkdir='mkdir -pv'
alias mv='mv -iv'
alias pp='python -mjson.tool'
alias rm='rm -iv'
alias sa='alias > ~/.bash_aliases'
alias svim='sudo vim -p'
alias svn-diff='svn diff --diff-cmd colordiff -x -uw'
alias svn-ydiff='svn --diff-cmd "diff" --extensions "-by -W250" diff'
alias vdir='vdir --color=auto'
alias vim='vim -p'
